import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Xinan Yang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <h1 className={styles.title}>XINAN YANG</h1>
          <a href="" className={styles.link}>
            PORTFOLIO
          </a>
          <a href="" className={styles.link}>
            ARTIST STATEMENT
          </a>
          <a href="" className={styles.link}>
            CV
          </a>
          <a href="" className={styles.link}>
            SOCIAL MEDIA
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
